name: Package Application with Pyinstaller

on:
  release:
    types: [published]
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: . 
        spec: metadata_writer.spec

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: metadata_writer.exe
    #     path: dist/

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/metadata_writer.exe
    # - name: Upload binaries to release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: dist/metadata_writer.exe
    #     asset_name: executable
    #     tag: ${{ github.ref }}
    #     overwrite: true
    #     body: "This is my release text"