name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: . 
        spec: metadata_writer.spec

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: metadata_writer.exe
    #     path: dist/

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/metadata_writer.exe